### ISSUE TITLE
[BUG] regex escapes for responses not correctly validated

### ISSUE THREAD

**Issue by Panaetius** [schemathesis/schemathesis#2749]
### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug

I have a schema that contains a regex for a docker image name, which uses escapes like `\\/` in the pattern. Since version 3.39.8, this fails tests with returned value not matching the pattern. This is likely due to the escape sequences not being handled correctly.

### To Reproduce

Please include a minimal API schema causing this issue:

the component schema as returned on the spec.json endpoint
```json
"ContainerImage": {
    "description": "A container image",
    "type": "string",
    "maxLength": 500,
    "pattern": "^[a-z0-9]+((\\.|_|__|-+)[a-z0-9]+)*(\\/[a-z0-9]+((\\.|_|__|-+)[a-z0-9]+)*)*(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}|@sha256:[a-fA-F0-9]{64}){0,1}$",
    "example": "renku/renkulab-py:3.10-0.18.1"
  }
```

Note the example is a value that will fail the schemathesis test (due to the `/`).

[schemathesis test this happens on](https://github.com/SwissDataScienceCenter/renku-data-services/blob/main/test/bases/renku_data_services/data_api/test_schemathesis.py#L91)

Example error log:
```
cls = <class 'jsonschema.validators.Draft4Validator'>
schema = {'description': 'A container image', 'example': 'renku/renkulab-py:3.10-0.18.1', 'pattern': '^([a-z0-9]){1,500}(\\.|_|...z0-9]+((\\.|_|__|-+)[a-z0-9]+)*){0}(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}|@sha256:[a-fA-F0-9]{64}){0}$', 'type': 'string'}
format_checker = <FormatChecker checkers=['date-time', 'email', 'hostname', 'idn-email', 'ipv4', 'ipv6', 'regex', 'uri']>

    @classmethod
    def check_schema(cls, schema, format_checker=_UNSET):
        Validator = validator_for(cls.META_SCHEMA, default=cls)
        if format_checker is _UNSET:
            format_checker = Validator.FORMAT_CHECKER
        validator = Validator(
            schema=cls.META_SCHEMA,
            format_checker=format_checker,
        )
        for error in validator.iter_errors(schema):
>           raise exceptions.SchemaError.create_from(error)
E           jsonschema.exceptions.SchemaError: '^([a-z0-9]){1,500}(\\.|_|__|-+)[a-z0-9]+){0}(\\/[a-z0-9]+((\\.|_|__|-+)[a-z0-9]+)*){0}(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}|@sha256:[a-fA-F0-9]{64}){0}$' is not a 'regex'
E           
E           Failed validating 'format' in metaschema['properties']['pattern']:
E               {'type': 'string', 'format': 'regex'}
E           
E           On schema['pattern']:
E               '^([a-z0-9]){1,500}(\\.|_|__|-+)[a-z0-9]+){0}(\\/[a-z0-9]+((\\.|_|__|-+)[a-z0-9]+)*){0}(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}|@sha256:[a-fA-F0-9]{64}){0}$'
E           while generating 'case' from one_of(get_case_strategy(operation=APIOperation(path='/session_launchers/{launcher_id}',
E            method='patch',
E            definition=,
E            schema=,
E            verbose_name='PATCH /api/data/session_launchers/{launcher_id}',
E            app=None,
E            base_url='/api/data',
E            path_parameters=,
E            headers=,
E            cookies=,
E            query=,
E            body=,
E            case_cls=), generation_config=GenerationConfig(allow_x00=True,
E            graphql_allow_null=True,
E            codec='utf-8',
E            with_security_parameters=True,
E            headers=HeaderConfig(strategy=None)), skip_on_not_negated=False), get_case_strategy(operation=APIOperation(path='/session_launchers/{launcher_id}',
E            method='patch',
E            definition=,
E            schema=,
E            verbose_name='PATCH /api/data/session_launchers/{launcher_id}',
E            app=None,
E            base_url='/api/data',
E            path_parameters=,
E            headers=,
E            cookies=,
E            query=,
E            body=,
E            case_cls=), generator=<DataGenerationMethod.negative: 'negative'>, generation_config=GenerationConfig(allow_x00=True,
E            graphql_allow_null=True,
E            codec='utf-8',
E            with_security_parameters=True,
E            headers=HeaderConfig(strategy=None)), skip_on_not_negated=False))
```

### Expected behavior

Test should not fail

### Environment

```
- OS: Linux
- Python version: 3.12
- Schemathesis version: 3.39.8+
- Spec version: Open API 3.0.2
```

**Comment by Stranger6667** [comment]
Thanks for reporting!

Right, it looks like a bug in merging of `pattern` with `maxLength`, which is done to make some combinations of these keywords possible to generate (in a realistic timespan).

I know about another bug in that logic (found by corpus tests), and planned to fix it over the weekend. So, I'll take a look at this one too!

Could you, please, point me to your API spec? I'll take a look at `pattern` keywords you use and will add test cases ensuring they are handled correctly

**Comment by Panaetius** [comment]
Thanks for the fast reply and for looking into it!

Yes you can find our complete API spec under https://renkulab.io/api/data/spec.json

**Comment by Stranger6667** [comment]
So, version `3.39.8` gives the following error:

```
Schema Error

Failed to generate test cases for this API operation because of unsupported regular expression `^([a-z0-9]){1,500}(\.|_|__|-+)[a-z0-9]+){0}(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*){0}(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}|@sha256:[a-fA-F0-9]{64}){0}$`

```

On this command:

```
st run https://renkulab.io/api/data/spec.json --base-url http://127.0.0.1:8081  --include-name='PATCH /session_launchers/{launcher_id}' -D all
```

Which internally appears to be triggered exactly by that issue (as the regex has unbalanced parentheses, and is displayed as a raw version where there are single `\` before `.`). 

`3.39.10` has the same behavior, but `3.39.11` works fine.

I've fixed another issue related to regular expressions in `3.39.12`. Could you, please, check the latest version?

**Comment by Panaetius** [comment]
I tested with `3.39.12` and unfortunately it still fails with
```
E       schemathesis.exceptions.CheckFailed:
E
E       1. Response violates schema
E
E           'renku/renkulab-py:3.10-0.18.1' does not match '^([a-z0-9]){1,500}((\\.|_|__|-+)[a-z0-9]+){0}(\\/[a-z0-9]+((\\.|_|__|-+)[a-z0-9]+)*){0}(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}|@sha256:[a-fA-F0-9]{64}){0}$'
E
E           Schema at /properties/container_image:
E
E               {
E                   "description": "A container image",
E                   "type": "string",
E                   "pattern": "^([a-z0-9]){1,500}((\\.|_|__|-+)[a-z0-9]+){0}(\\/[a-z0-9]+((\...
E                   "example": "renku/renkulab-py:3.10-0.18.1"
E               }
E
E           Value:
E
E               "renku/renkulab-py:3.10-0.18.1"
E
E       [201] Created:
E
E           `{"id":"01JNJV22Q3DBXP7VPK5E0KVG7Z","name":"My Renku Session :)","creation_date":"2025-03-05T09:44:16Z","container_image":"renku/renkulab-py:3.10-0.18.1","default_url":"/lab","uid":1000,"gid":1000,"working_directory":"/home/jovyan/work","mount_directory":"/home/jovyan/work","port":8080,"is_archived":false}`
E
E       Reproduce with:
E
E           curl -X POST -H 'host: mockserver:1234' -H 'authorization: Bearer {"is_admin": true, "id": "admin", "name": "Admin Doe", "first_name": "Admin", "last_name": "Doe", "email": "admin.doe@gmail.com", "full_name": "Admin Doe"}' -H 'content-type: application/json' -d '{"name": "My Renku Session :)", "container_image": "renku/renkulab-py:3.10-0.18.1", "default_url": "/lab", "working_directory": "/home/jovyan/work", "mount_directory": "/home/jovyan/work"}' http://localhost/api/data/environments
E
E       Falsifying explicit example: async_run(
E           sanic_client=<test.utils.SanicReusableASGITestClient object at 0x7402717c03b0>,
E           admin_headers={'Authorization': 'Bearer {"is_admin": true, "id": "admin", "name": "Admin Doe", "first_name": "Admin", "last_name": "Doe", "email": "admin.doe@gmail.com", "full_name": "Admin Doe"}'},
E           requests_statistics=RequestsStatistics(len=465),
E           case=,
E       )
```

what's odd to me is, in the error you got, the part at the beginning of the regex `^([a-z0-9]){1,500}(\.|_|__|-+)[a-z0-9]+){0}` which has unbalanced parenthesis but if I access the link to our spec, it looks like `"pattern":"^[a-z0-9]+((\\.|_|__|-+)[a-z0-9]+)*(\\/[a-z0-9]+((\\.|_|__|-+)[a-z0-9]+)*)*(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}|@sha256:[a-fA-F0-9]{64}){0,1}$"` so there's something other than just escaping going on it seems? specifically, the {1,500} is not in the pattern on our side, though I assume that was added due to the min and max length constraints? and it seems that instead of a `*` in your error message there's a `{0}`
